# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SparseRowVar2 <- function(mat, mu) {
    .Call('_spatialGE_SparseRowVar2', PACKAGE = 'spatialGE', mat, mu)
}

SparseRowVarStd <- function(mat, mu, sd, vmax) {
    .Call('_spatialGE_SparseRowVarStd', PACKAGE = 'spatialGE', mat, mu, sd, vmax)
}

computeSubsampleSums <- function(coords, n_subsample, n_samples) {
    .Call('_spatialGE_computeSubsampleSums', PACKAGE = 'spatialGE', coords, n_subsample, n_samples)
}

